// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAya22Cs0vocuyUBm51uaEHgb0JiD2nKFg',
    appId: '1:573104143576:web:842b0bd111384a4183abad',
    messagingSenderId: '573104143576',
    projectId: 'csoc-flutter',
    authDomain: 'csoc-flutter.firebaseapp.com',
    storageBucket: 'csoc-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB42XoEuBTw_2krNmMKKPway79kHdtE12o',
    appId: '1:573104143576:android:f4a33d3cb244390683abad',
    messagingSenderId: '573104143576',
    projectId: 'csoc-flutter',
    storageBucket: 'csoc-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACvz96YfH7ca3lGcLARm2trRTtKKoKUkM',
    appId: '1:573104143576:ios:baea513750b0b40683abad',
    messagingSenderId: '573104143576',
    projectId: 'csoc-flutter',
    storageBucket: 'csoc-flutter.appspot.com',
    androidClientId: '573104143576-lsb54i6fkjps3eb09cgkqts4vfqlvk4v.apps.googleusercontent.com',
    iosClientId: '573104143576-89oqfp9kva9c4e5f4hh1i7kb1vrle6qu.apps.googleusercontent.com',
    iosBundleId: 'com.example.csocFlutter',
  );

}